# Generated by Django 4.2 on 2024-10-20 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
        ('examenes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallesExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaEntrega', models.DateField(verbose_name='Fecha entrega')),
                ('precio', models.FloatField(verbose_name='Precio')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='consultas.consulta', verbose_name='Consulta')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='examenes.examen', verbose_name='Examen')),
            ],
            options={
                'verbose_name_plural': 'Detalle de Examenes',
            },
        ),
    ]
