# Generated by Django 4.2 on 2024-10-28 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0002_detallesexamen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examen',
            name='costo',
        ),
        migrations.AlterField(
            model_name='detallesexamen',
            name='examen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='examenes.examen', verbose_name='Examen'),
        ),
    ]
