# Generated by Django 4.2 on 2024-09-16 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoProducto', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('nombreProducto', models.CharField(max_length=100, verbose_name='Nombre')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('fechaVencimiento', models.DateField(max_length=200, verbose_name='Fecha vencimiento')),
                ('precio', models.FloatField(verbose_name='Precio')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.categoria', verbose_name='Categoria')),
                ('medidas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.medidas', verbose_name='Unidas de Medidas')),
                ('presentaciones', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.presentaciones', verbose_name='Presentaciones')),
            ],
            options={
                'verbose_name_plural': 'Producto',
            },
        ),
    ]
