# Generated by Django 4.2 on 2024-10-20 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('fecha', models.DateField(verbose_name='Fecha de consulta')),
                ('clienteId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.clientes', verbose_name='Cliente')),
            ],
            options={
                'verbose_name_plural': 'Consultas',
            },
        ),
    ]
