# Generated by Django 4.2 on 2024-10-06 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('tipoEstado', models.CharField(max_length=50, verbose_name='Tipo de estado')),
            ],
            options={
                'verbose_name_plural': 'Tipo de estado',
            },
        ),
    ]
