# Generated by Django 4.2 on 2024-10-29 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0003_remove_examen_costo_alter_detallesexamen_examen'),
        ('resultado', '0002_resultadoexamen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadoexamen',
            name='detalleExamen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='examenes.detallesexamen', verbose_name='Detalle de Examen'),
        ),
        migrations.AlterField(
            model_name='resultadoexamen',
            name='resultado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='resultado.resultado', verbose_name='Resultado'),
        ),
    ]
