# Generated by Django 4.2 on 2024-09-16 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('nombres', models.CharField(max_length=50, verbose_name='Nombres')),
                ('primerApellido', models.CharField(max_length=50, verbose_name='Primer Apellido')),
                ('segundoApellido', models.CharField(max_length=50, verbose_name='Segundo Apellido')),
                ('direccion', models.CharField(max_length=50, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=50, unique=True, verbose_name='Teléfono')),
            ],
            options={
                'verbose_name_plural': 'Registro de clientes',
            },
        ),
    ]
