# Generated by Django 4.2 on 2024-10-06 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipoFactura', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('fecha', models.DateField(verbose_name='Fecha Factura')),
                ('iva', models.FloatField(max_length=50, verbose_name='Iva')),
                ('descuento', models.FloatField(max_length=50, verbose_name='Descuento')),
                ('clienteId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.clientes', verbose_name='Cliente')),
                ('tipoFacturaId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tipoFactura.tipofacturas', verbose_name='Tipo factura')),
            ],
            options={
                'verbose_name_plural': 'Facturas',
            },
        ),
    ]
