# Generated by Django 4.2 on 2024-10-06 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('detalleExamen', '0001_initial'),
        ('estado', '0001_initial'),
        ('resultado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(verbose_name='Valor')),
                ('detalleExamen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='detalleExamen.detallesexamen', verbose_name='Detalle de Examen')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estado.estado', verbose_name='Estado')),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='resultado.resultado', verbose_name='Resultado')),
            ],
            options={
                'verbose_name_plural': 'Resultados de Examenes',
            },
        ),
    ]
