# Generated by Django 4.2 on 2024-10-06 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipoCompra', '0001_initial'),
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('proveedorId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proveedores.proveedores', verbose_name='Proveedor')),
                ('tipoDeCompraId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tipoCompra.tipocompras', verbose_name='Tipo de compra')),
            ],
            options={
                'verbose_name_plural': 'Compras',
            },
        ),
    ]
