# Generated by Django 4.2 on 2024-10-27 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_departamento_municipio_sucursal'),
        ('compras', '0003_alter_detallescompras_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='sucursal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='catalogos.sucursal', verbose_name='Sucursal'),
            preserve_default=False,
        ),
    ]
